debug: false

#feign:
#  hystrix:
#    enabled: true

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
#  client:
#    healthcheck:
#      enabled: true
#  client:
#    serviceUrl:
#      defaultZone: http://admin:123456@${myenv.hostname}:8010/eureka/,http://admin:123456@${myenv.hostname}:8011/eureka/,http://admin:123456@${myenv.hostname}:8012/eureka/
#      defaultZone: http://${myenv.hostname}:8010/eureka/,http://${myenv.hostname}:8011/eureka/,http://${myenv.hostname}:8012/eureka/


zuul:
  routes:
    api-a:
      path: /aaa/**
      serviceId: eureka-client1
    api-b:
      path: /bbb/**
      serviceId: eureka-client2

spring:
  profiles:
    active: server1
  zipkin:
    base-url: http://${myenv.hostname}:8060/
  sleuth:
    sampler:
      percentage: 1
---
spring:
  profiles: server1

server:
  port: 8050

---
spring:
  profiles: server2

server:
  port: 8051