package com.example.client.demo.vo;

import java.util.Date;

public class TEasConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.id
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.client_id
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private Long clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.company_number
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private String companyNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.eas_dcname
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private String easDcname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.eas_dbtype
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private Integer easDbtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.eas_language
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private String easLanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.eas_slnname
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private String easSlnname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.eas_username
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private String easUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.eas_password
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private String easPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.eas_wsdl_login
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private String easWsdlLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.eas_wsdl_voucher
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private String easWsdlVoucher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.create_by
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.create_time
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.update_by
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eas_config.update_time
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.id
     *
     * @return the value of t_eas_config.id
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.id
     *
     * @param id the value for t_eas_config.id
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.client_id
     *
     * @return the value of t_eas_config.client_id
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.client_id
     *
     * @param clientId the value for t_eas_config.client_id
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.company_number
     *
     * @return the value of t_eas_config.company_number
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public String getCompanyNumber() {
        return companyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.company_number
     *
     * @param companyNumber the value for t_eas_config.company_number
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setCompanyNumber(String companyNumber) {
        this.companyNumber = companyNumber == null ? null : companyNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.eas_dcname
     *
     * @return the value of t_eas_config.eas_dcname
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public String getEasDcname() {
        return easDcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.eas_dcname
     *
     * @param easDcname the value for t_eas_config.eas_dcname
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setEasDcname(String easDcname) {
        this.easDcname = easDcname == null ? null : easDcname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.eas_dbtype
     *
     * @return the value of t_eas_config.eas_dbtype
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public Integer getEasDbtype() {
        return easDbtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.eas_dbtype
     *
     * @param easDbtype the value for t_eas_config.eas_dbtype
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setEasDbtype(Integer easDbtype) {
        this.easDbtype = easDbtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.eas_language
     *
     * @return the value of t_eas_config.eas_language
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public String getEasLanguage() {
        return easLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.eas_language
     *
     * @param easLanguage the value for t_eas_config.eas_language
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setEasLanguage(String easLanguage) {
        this.easLanguage = easLanguage == null ? null : easLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.eas_slnname
     *
     * @return the value of t_eas_config.eas_slnname
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public String getEasSlnname() {
        return easSlnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.eas_slnname
     *
     * @param easSlnname the value for t_eas_config.eas_slnname
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setEasSlnname(String easSlnname) {
        this.easSlnname = easSlnname == null ? null : easSlnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.eas_username
     *
     * @return the value of t_eas_config.eas_username
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public String getEasUsername() {
        return easUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.eas_username
     *
     * @param easUsername the value for t_eas_config.eas_username
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setEasUsername(String easUsername) {
        this.easUsername = easUsername == null ? null : easUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.eas_password
     *
     * @return the value of t_eas_config.eas_password
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public String getEasPassword() {
        return easPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.eas_password
     *
     * @param easPassword the value for t_eas_config.eas_password
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setEasPassword(String easPassword) {
        this.easPassword = easPassword == null ? null : easPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.eas_wsdl_login
     *
     * @return the value of t_eas_config.eas_wsdl_login
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public String getEasWsdlLogin() {
        return easWsdlLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.eas_wsdl_login
     *
     * @param easWsdlLogin the value for t_eas_config.eas_wsdl_login
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setEasWsdlLogin(String easWsdlLogin) {
        this.easWsdlLogin = easWsdlLogin == null ? null : easWsdlLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.eas_wsdl_voucher
     *
     * @return the value of t_eas_config.eas_wsdl_voucher
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public String getEasWsdlVoucher() {
        return easWsdlVoucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.eas_wsdl_voucher
     *
     * @param easWsdlVoucher the value for t_eas_config.eas_wsdl_voucher
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setEasWsdlVoucher(String easWsdlVoucher) {
        this.easWsdlVoucher = easWsdlVoucher == null ? null : easWsdlVoucher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.create_by
     *
     * @return the value of t_eas_config.create_by
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.create_by
     *
     * @param createBy the value for t_eas_config.create_by
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.create_time
     *
     * @return the value of t_eas_config.create_time
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.create_time
     *
     * @param createTime the value for t_eas_config.create_time
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.update_by
     *
     * @return the value of t_eas_config.update_by
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.update_by
     *
     * @param updateBy the value for t_eas_config.update_by
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eas_config.update_time
     *
     * @return the value of t_eas_config.update_time
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eas_config.update_time
     *
     * @param updateTime the value for t_eas_config.update_time
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}