package com.example.client.demo.mapper;

import com.example.client.demo.vo.TAccountTest;
import java.util.List;

public interface TAccountTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_test
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_test
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    int insert(TAccountTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_test
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    TAccountTest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_test
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    List<TAccountTest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_test
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    int updateByPrimaryKey(TAccountTest record);
}