package com.example.client.demo.mapper;

import com.example.client.demo.vo.TEasConfig;
import java.util.List;

public interface TEasConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eas_config
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eas_config
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    int insert(TEasConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eas_config
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    TEasConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eas_config
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    List<TEasConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eas_config
     *
     * @mbg.generated Fri Mar 30 15:45:04 CST 2018
     */
    int updateByPrimaryKey(TEasConfig record);
}