debug: false

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
#  client:
#    serviceUrl:
#      defaultZone: http://admin:123456@${myenv.hostname}:8010/eureka/,http://admin:123456@${myenv.hostname}:8011/eureka/,http://admin:123456@${myenv.hostname}:8012/eureka/
#      defaultZone: http://${myenv.hostname}:8010/eureka/,http://${myenv.hostname}:8011/eureka/,http://${myenv.hostname}:8012/eureka/
spring:
  profiles:
    active: server1
  zipkin:
    base-url: http://${myenv.hostname}:8060/
  sleuth:
    sampler:
      percentage: 1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&generateSimpleParameterMetadata=true
    username: springcloud
    password: springcloud
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    charset: utf-8
    cache: false
    template-loader-path: classpath:/templates/
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    request-context-attribute: request

logging:
  level:
    root: INFO
    org.mybatis: debug
    org.springframework.transaction: INFO
    com.example.freemarker.demo.mapper: debug

mybatis:
#  typeAliasesPackage: com.example.client.demo.vo
  mapperLocations: classpath:mapper/*.xml


---
spring:
  profiles: server1

server:
  port: 8070

---
spring:
  profiles: server2

server:
  port: 8071