package com.example.freemarker.demo.mapper;

import com.example.freemarker.demo.entity.TAccountTest;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TAccountTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_test
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_test
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    int insert(TAccountTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_test
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    TAccountTest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_test
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    List<TAccountTest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_test
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    int updateByPrimaryKey(TAccountTest record);
}