package com.example.freemarker.demo.entity;

import java.math.BigDecimal;

public class TAccountTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_test.id
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_test.name
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_test.money
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    private BigDecimal money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_test.id
     *
     * @return the value of t_account_test.id
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_test.id
     *
     * @param id the value for t_account_test.id
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_test.name
     *
     * @return the value of t_account_test.name
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_test.name
     *
     * @param name the value for t_account_test.name
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_test.money
     *
     * @return the value of t_account_test.money
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_test.money
     *
     * @param money the value for t_account_test.money
     *
     * @mbg.generated Fri Mar 30 16:51:59 CST 2018
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
}